title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://everythingsmarthome.github.io

aux_links:
  Template Repository: https://everythingsmarthome.github.io/everything-presence-one-docs
